services:
  overseerrtelegramapprover:
    container_name: overseerr-telegram-approver
    image: xnotorious/overseerr-telegram-approver
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_BOT_TOKEN: "your-telegram-bot-token"
      TELEGRAM_CHAT_ID: "your-telegram-chat-id"
      OVERSEERR_API_URL: "http://your-overseerr-url/api/v1"
      OVERSEERR_API_KEY: "your-overseerr-api-key"
      WEBHOOK_SECRET: "your-webhook-secret"
      PORT: 8080
      ADMIN_PASSWORD_HASH: 'your-hashed-admin-password' # See README how to get your hashed password
      ADMINS_FILE: "data/admins.json"
      USERS_FILE: "data/users.json"
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, http.client; conn = http.client.HTTPConnection('localhost', 8080); conn.request('GET', '/health'); sys.exit(0) if conn.getresponse().status == 200 else sys.exit(1)"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s